pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      sudo apt-get install -y ninja-build
    displayName: Install rust
  - script: cargo build -vv --all
    displayName: Cargo build
  - script: cargo test -vv --all
    displayName: Cargo test
