[package]
name = "cargo_gn"
version = "0.0.2"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

description = "Cargo integration with the GN build system"
license = "MIT"

[workspace]
members = [
  "example",
  ".",
]

[dependencies]
